repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    - id: isort
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.2
    hooks:
    -   id: pylint
        args:
        - --disable=W,R,C
        - --rcfile=.pylintrc
        - --jobs=1
        name: Pylint
        language: system
        types: [python]
